### ISSUE TITLE
No folder write permission on OSX & Linux

### ISSUE THREAD

**Issue by STRND** [gregzaal/filmic-blender-add-on#2]
MacBook Pro 2016 Touchbar:
I created a folder in my applications called 'addon' and put your file in there. I then pressed the button in blender and this came up in red:

Traceback (most recent call last):
  File "/Users/strnd/Library/Application Support/Blender/2.78/scripts/addons/filmic_blender.py", line 57, in execute
    os.rename(cmpath, opath)
OSError: [Errno 30] Read-only file system: '/private/var/folders/n7/fhpx1n852sdg_xfzn02zm2jwmxt2vm/T/AppTranslocation/183AF043-928A-4D34-91DD-BF40165F1961/d/blender.app/Contents/Resources/2.78/datafiles/colormanagement' -> '/private/var/folders/n7/fhpx1n852sdg_xfzn02zm2jwmxt2vm/T/AppTranslocation/183AF043-928A-4D34-91DD-BF40165F1961/d/blender.app/Contents/Resources/2.78/datafiles/colormanagement_old'

location: <unknown location>:-1

Traceback (most recent call last):
  File "/Users/strnd/Library/Application Support/Blender/2.78/scripts/addons/filmic_blender.py", line 57, in execute
    os.rename(cmpath, opath)
OSError: [Errno 30] Read-only file system: '/private/var/folders/n7/fhpx1n852sdg_xfzn02zm2jwmxt2vm/T/AppTranslocation/183AF043-928A-4D34-91DD-BF40165F1961/d/blender.app/Contents/Resources/2.78/datafiles/colormanagement' -> '/private/var/folders/n7/fhpx1n852sdg_xfzn02zm2jwmxt2vm/T/AppTranslocation/183AF043-928A-4D34-91DD-BF40165F1961/d/blender.app/Contents/Resources/2.78/datafiles/colormanagement_old'

location: <unknown location>:-1

**Comment by gregzaal** [comment]
Sounds like a problem with the folder permissions, but since I don't have a Mac to test with I don't think I can solve this now.

**Comment by sphinxc0re** [comment]
I have the same problem with Ubuntu 16.04. Here is a screenshot:
![screenshot from 2017-02-25 18-25-19](https://cloud.githubusercontent.com/assets/3702016/23333248/b699c97e-fb88-11e6-8780-8106519b3a0c.png)

**Comment by gregzaal** [comment]
I guess in linux it has to be run with sudo, unless you store blender somewhere that you have permission to write to

**Comment by sphinxc0re** [comment]
Pity! I want the ease of updating so badly

**Comment by gregzaal** [comment]
Did you install blender from one of the linux package managers (apt-get)? Those are usually problematic for a variety of reasons. Better to get it from blender.org or builder.blender.org.

**Comment by STRND** [comment]
Removed add on and move blender out of my applications folder and into documents. Added add on again and keep getting this:

Traceback (most recent call last):
  File "/Users/strnd/Library/Application Support/Blender/2.78/scripts/addons/filmic_blender.py", line 57, in execute
    os.rename(cmpath, opath)
OSError: [Errno 30] Read-only file system: '/private/var/folders/n7/fhpx1n852sdg_xfzn02zm2jwmxt2vm/T/AppTranslocation/06C28B33-B209-4B2F-9E8D-779EFA3AF4CD/d/blender.app/Contents/Resources/2.78/datafiles/colormanagement' -> '/private/var/folders/n7/fhpx1n852sdg_xfzn02zm2jwmxt2vm/T/AppTranslocation/06C28B33-B209-4B2F-9E8D-779EFA3AF4CD/d/blender.app/Contents/Resources/2.78/datafiles/colormanagement_old'

location: <unknown location>:-1


Read-only file system? I have Sophos installed on system but can't see how that would be an issue with permissions.I'm not sure how I can fix this. Any suggestions as I think your add on is a great way to update Filmic on Blender and I would like to say thank you for the time to make this add on.

**Comment by STRND** [comment]
<img width="1667" alt="screen shot 2017-02-25 at 22 08 13" src="https://cloud.githubusercontent.com/assets/7806220/23335150/fc50c15c-fba6-11e6-884d-ada37e2a6eae.png">

**Comment by gregzaal** [comment]
For Linux users, just start blender from a terminal with `sudo blender`, then it'll have permission to write to that folder. No idea what the sudo equivalent for OSX is.

**Comment by sphinxc0re** [comment]
It's `sudo` 😁

**Comment by sphinxc0re** [comment]
Isn't there another way? Can't you open a password prompt or something?

**Comment by gregzaal** [comment]
No idea, someone with experience with this should help out.

**Comment by joshring** [comment]
The easiest way to adjust on Linux (and mac) is to use the environment variable approach:

"export OCIO=/path/to/where/the/filmic-blender/config.ocio"
So put export OCIO=cpath or something similar in the code and all will be well for both mac and linux.

See the discussion about the environment variable here:
https://github.com/sobotka/filmic-blender

That should be modifiable without sudo etc

**Comment by FirefoxMetzger** [comment]
I ran into the same issue on Windows 10 today. It's in a different line though.
![screenshot](https://user-images.githubusercontent.com/4402489/27803967-3212a314-6024-11e7-9628-76280565e64a.png)

Edit: Found a solution and its the same as on another OS: run as administrator.
